Groupe1.Webzine/Groupe1.Webzine.WebApplication/Controllers/ArtisteController.cs
using Microsoft.AspNetCore.Mvc;
using Groupe1.Webzine.WebApplication.ViewModels;
using Groupe1.Webzine.Repository.Contracts;

namespace Groupe1.Webzine.WebApplication.Controllers
{
    /// <summary>
    /// Controller de la page Artiste
    /// </summary>
    /// <returns></returns>
    public class ArtisteController : Controller
    {
        private IArtisteRepository _repository { get; set; }
        public ArtisteController(IArtisteRepository iArtiste)
        {
            _repository = iArtiste;
        }

        /// <summary>
        /// Appel de la vue index dans le dossier views/artiste
        /// </summary>
        /// <returns></returns>
        [Route("Artiste/{nom}")]
        public IActionResult Index(string nom)
        {
            var artiste = _repository.Find(nom);
            var model = new ArtisteIndexVM
            {
                NomArtiste = artiste.Nom,
                BioArtiste = artiste.Biographie,
                Titres = artiste.Titres
            };
            return View(model);
        }

        
}
}

Groupe1.Webzine/Groupe1.Webzine.WebApplication/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Groupe1.Webzine.WebApplication.Controllers
{
    /// <summary>
    /// Controller de la page contact
    /// </summary>
    public class ContactController : Controller
    {
        /// <summary>
        /// Appel de la vue Index dans le dossier Views/Contact
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

Groupe1.Webzine/Groupe1.Webzine.WebApplication/Controllers/RechercheController.cs
using Groupe1.Webzine.Business.Contracts;
using Groupe1.Webzine.Repository.Contracts;
using Groupe1.Webzine.WebApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Groupe1.Webzine.WebApplication.Controllers
{
    /// <summary>
    /// Controller pour les recherches
    /// </summary>
    public class RechercheController : Controller
    {
        private ITitreRepository _repositoryT { get; set; }
        private IArtisteRepository _repositoryA { get; set; }
        private ITime _time { get; set; }

        public RechercheController(ITitreRepository iTitre, IArtisteRepository iArtiste, ITime iTime)
        {
            _repositoryT = iTitre;
            _repositoryA = iArtiste;
            _time = iTime;
        }

        /// <summary>
        /// Appel de la vue Index
        /// </summary>
        /// <param name="query">Ce que l'utilisateur a recherché</param>
        /// <returns></returns>
        [Route("Recherche/{query?}")]
        public IActionResult Index(string query)
        {
            // Artistes trouvés avec la recherche
            var artistes = _repositoryA.FindAll().Where(a => a.Nom.ToLower().Contains(query.ToLower())).ToList();
            // Titres trouvés avec la recherche 
            var titres = _repositoryT.Search(query).ToList();

            // Titres appartenant aux artistes trouvés de la recherche
            //var titresArtistesTrouves = _repositoryT.FindAll().Where(t => t.Artiste.Nom.ToLower().Contains(query.ToLower())).ToList();
            // Liste finale des titres
            //titres.AddRange(titresArtistesTrouves);

            List<TitreVM> titresVM = new List<TitreVM>();
            
            foreach (var titre in titres)
            {
                var titreVM = new TitreVM();
                titreVM.Album = titre.Album;
                titreVM.Artiste = titre.Artiste;
                titreVM.Chronique = titre.Chronique;
                titreVM.Commentaires = titre.Commentaires;
                titreVM.DateCreation = titre.DateCreation;
                titreVM.DateSortie = titre.DateSortie;
                titreVM.Duree = titre.Duree;
                titreVM.IdArtiste = titre.IdArtiste;
                titreVM.IdTitre = titre.IdTitre;
                titreVM.Libelle = titre.Libelle;
                titreVM.NbLectures = titre.NbLectures;
                titreVM.NbLikes = titre.NbLikes;
                titreVM.Time = _time.SecondsConverter(titre.Duree);
                titreVM.TitresStyles = titre.TitresStyles;
                titreVM.UrlEcoute = titre.UrlEcoute;
                titreVM.UrlJaquette = titre.UrlJaquette;
                titresVM.Add(titreVM);
            }
            var model = new RechercheVM
            {
                Artistes = artistes,
                Titres = titresVM
            };
            ViewBag.Query = query;
            return View(model);
        }
    }
}

Groupe1.Webzine/Groupe1.Webzine.WebApplication/Controllers/StyleController.cs
using Groupe1.Webzine.Repository.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Groupe1.Webzine.WebApplication.Controllers
{
    /// <summary>
    /// Controller de la page Style
    /// </summary>
    /// <returns></returns>
    public class StyleController : Controller
    {
        private ITitreRepository _repositoryT { get; set; }
        private IStyleRepository _repositoryS { get; set; }

        public StyleController(ITitreRepository iTItre, IStyleRepository iStyle)
        {
            _repositoryT = iTItre;
            _repositoryS = iStyle;
        }

        /// <summary>
        /// Appel de la vue dans le dossier views/style
        /// </summary>
        /// <returns>Les musiques associées au style</returns>
        public IActionResult Index(int id)
        {
            var style = _repositoryS.Find(id);
            var titres = _repositoryT.SearchByStyle(style.Libelle);
            var model = new ViewModels.StyleIndexVM
            {
                LibelleStyle = style.Libelle,
                Titres = titres.ToList()
            };
            return View(model);
        }

        public IActionResult Index(string name)
        {
            var style = _repositoryS.Find(name);
            var titres = _repositoryT.SearchByStyle(style.Libelle);
            var model = new ViewModels.StyleIndexVM
            {
                LibelleStyle = style.Libelle,
                Titres = titres.ToList()
            };
            return View(model);
        }
    }
}

Groupe1.Webzine/Groupe1.Webzine.WebApplication/Views/Shared/_Squelette.cshtml
@addTagHelper*,Microsoft.AspNetCore.Mvc.TagHelpers
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="~/lib/bootstrap-5.0.0-beta1-dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap-5.0.0-beta1-dist/js/bootstrap.js"></script>
    <script src="~/fontawesome/fontawesome-free-5.15.1-web/js/all.js"></script>
    <link href="~/Style/main.css" rel="stylesheet" />
    
    <title>Webzine</title>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Webzine</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item d-flex">
                        <i class="fas fa-home m-auto"></i>
                        <a class="nav-link text-light" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                    </li>
                    <li class="nav-item dropdown d-flex">
                        <i class="fas fa-tools m-auto"></i>
                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Administration
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="Artiste" asp-action="Index">Artistes</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="Titre" asp-action="Index">Titres</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="Style" asp-action="Index">Styles</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="Commentaire" asp-action="Index">Commentaires</a></li>
                        </ul>
                    </li>
                    <li class="nav-item d-flex">
                        <i class="fas fa-envelope m-auto"></i>
                        <a class="nav-link text-light" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                    </li>
                </ul>
                <form class="d-flex m-auto me-0" asp-area="" asp-controller="Recherche" asp-action="Index">
                    <input name="query" class="form-control me-2" type="search" placeholder="Trouver un artiste / titre" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </nav>

    <div class="row">
        @if (ViewContext.RouteData.Values["area"] == null)
        {
            <div class="col-md-9">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
            <div class="col-md-3">
                @await Component.InvokeAsync("SideBar")
            </div>
        }
        else
        {
            <div class="col-12">
                @RenderBody()
            </div>
        }
    </div>

    <footer class="bg-light text-center text-lg-start mt-3">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: #F1EFEF">
            © ASP.NET Core - DIIAGE 2020 - 2021
        </div>
        <!-- Copyright -->
    </footer>
</body>
</html>